/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CapacityestimatevaluesGetResponseEstimateValuesInner
 */
export interface CapacityestimatevaluesGetResponseEstimateValuesInner {
    /**
     * 
     * @type {string}
     * @memberof CapacityestimatevaluesGetResponseEstimateValuesInner
     */
    'id'?: string;
    /**
     * 
     * @type {any}
     * @memberof CapacityestimatevaluesGetResponseEstimateValuesInner
     */
    'team_id'?: any | null;
    /**
     * 
     * @type {any}
     * @memberof CapacityestimatevaluesGetResponseEstimateValuesInner
     */
    'team_membership_id'?: any | null;
    /**
     * 
     * @type {string}
     * @memberof CapacityestimatevaluesGetResponseEstimateValuesInner
     */
    'period_start'?: string;
    /**
     * 
     * @type {number}
     * @memberof CapacityestimatevaluesGetResponseEstimateValuesInner
     */
    'total'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CapacityestimatevaluesGetResponseEstimateValuesInner
     */
    'computed'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CapacityestimatevaluesGetResponseEstimateValuesInner
     */
    'ignored'?: boolean;
}

