/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AssistantusageGetResponsePagination } from './assistantusage-get-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import type { CapacityinvestmentsGetResponseCapacityInvestmentsInner } from './capacityinvestments-get-response-capacity-investments-inner';

/**
 * 
 * @export
 * @interface CapacityinvestmentsGetResponse
 */
export interface CapacityinvestmentsGetResponse {
    /**
     * 
     * @type {Array<CapacityinvestmentsGetResponseCapacityInvestmentsInner>}
     * @memberof CapacityinvestmentsGetResponse
     */
    'capacity_investments'?: Array<CapacityinvestmentsGetResponseCapacityInvestmentsInner>;
    /**
     * 
     * @type {AssistantusageGetResponsePagination}
     * @memberof CapacityinvestmentsGetResponse
     */
    'pagination'?: AssistantusageGetResponsePagination;
}

