/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CapacityscenariosGetResponseCapacityScenario
 */
export interface CapacityscenariosGetResponseCapacityScenario {
    /**
     * 
     * @type {number}
     * @memberof CapacityscenariosGetResponseCapacityScenario
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CapacityscenariosGetResponseCapacityScenario
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CapacityscenariosGetResponseCapacityScenario
     */
    'planning_interval'?: string;
    /**
     * 
     * @type {string}
     * @memberof CapacityscenariosGetResponseCapacityScenario
     */
    'planning_start_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof CapacityscenariosGetResponseCapacityScenario
     */
    'planning_end_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof CapacityscenariosGetResponseCapacityScenario
     */
    'estimate_value_layout'?: string;
    /**
     * 
     * @type {string}
     * @memberof CapacityscenariosGetResponseCapacityScenario
     */
    'data_entry_units'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CapacityscenariosGetResponseCapacityScenario
     */
    'archived'?: boolean;
}

