/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomreportsGetResponseFieldDefinitions7
 */
export interface CustomreportsGetResponseFieldDefinitions7 {
    /**
     * 
     * @type {number}
     * @memberof CustomreportsGetResponseFieldDefinitions7
     */
    'ref'?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomreportsGetResponseFieldDefinitions7
     */
    'table'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomreportsGetResponseFieldDefinitions7
     */
    'field'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomreportsGetResponseFieldDefinitions7
     */
    'title'?: string;
}

