/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CustomtablerecordsPostRequestCustomObjectRecordCustomFields } from './customtablerecords-post-request-custom-object-record-custom-fields';

/**
 * 
 * @export
 * @interface CustomtablerecordsPostRequestCustomObjectRecord
 */
export interface CustomtablerecordsPostRequestCustomObjectRecord {
    /**
     * 
     * @type {CustomtablerecordsPostRequestCustomObjectRecordCustomFields}
     * @memberof CustomtablerecordsPostRequestCustomObjectRecord
     */
    'custom_fields'?: CustomtablerecordsPostRequestCustomObjectRecordCustomFields;
}

