/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomfieldoptionsDeleteResponse
 */
export interface CustomfieldoptionsDeleteResponse {
    /**
     * 
     * @type {string}
     * @memberof CustomfieldoptionsDeleteResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomfieldoptionsDeleteResponse
     */
    'value'?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomfieldoptionsDeleteResponse
     */
    'color'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CustomfieldoptionsDeleteResponse
     */
    'hidden'?: boolean;
}

