/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomtablerecordsPutResponseCustomObjectRecordLinkedRecordsInner
 */
export interface CustomtablerecordsPutResponseCustomObjectRecordLinkedRecordsInner {
    /**
     * 
     * @type {string}
     * @memberof CustomtablerecordsPutResponseCustomObjectRecordLinkedRecordsInner
     */
    'key'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomtablerecordsPutResponseCustomObjectRecordLinkedRecordsInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomtablerecordsPutResponseCustomObjectRecordLinkedRecordsInner
     */
    'record_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomtablerecordsPutResponseCustomObjectRecordLinkedRecordsInner
     */
    'record_id'?: string;
}

