/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeletionsPostResponseDeletionRecord
 */
export interface DeletionsPostResponseDeletionRecord {
    /**
     * 
     * @type {string}
     * @memberof DeletionsPostResponseDeletionRecord
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeletionsPostResponseDeletionRecord
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof DeletionsPostResponseDeletionRecord
     */
    'reference_num'?: string;
}

