/* tslint:disable */
/* eslint-disable */
/**
 * Aha! REST API
 * API for interacting with Aha! product management platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EpicDescription
 */
export interface EpicDescription {
    /**
     * 
     * @type {string}
     * @memberof EpicDescription
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EpicDescription
     */
    'body'?: string;
    /**
     * 
     * @type {string}
     * @memberof EpicDescription
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof EpicDescription
     */
    'updated_at'?: string;
}

