/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EpicsPostResponseEpicWorkflowStatusTimesInner
 */
export interface EpicsPostResponseEpicWorkflowStatusTimesInner {
    /**
     * 
     * @type {string}
     * @memberof EpicsPostResponseEpicWorkflowStatusTimesInner
     */
    'status_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EpicsPostResponseEpicWorkflowStatusTimesInner
     */
    'status_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EpicsPostResponseEpicWorkflowStatusTimesInner
     */
    'started_at'?: string;
    /**
     * 
     * @type {any}
     * @memberof EpicsPostResponseEpicWorkflowStatusTimesInner
     */
    'ended_at'?: any | null;
}

