/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EpicsPutResponseEpicCreatedByUser
 */
export interface EpicsPutResponseEpicCreatedByUser {
    /**
     * 
     * @type {string}
     * @memberof EpicsPutResponseEpicCreatedByUser
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EpicsPutResponseEpicCreatedByUser
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof EpicsPutResponseEpicCreatedByUser
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof EpicsPutResponseEpicCreatedByUser
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof EpicsPutResponseEpicCreatedByUser
     */
    'updated_at'?: string;
}

