/* tslint:disable */
/* eslint-disable */
/**
 * Aha! REST API
 * API for interacting with Aha! product management platform.  ## Rate Limiting The API enforces rate limits to ensure fair usage: - **300 requests per minute** per account - **20 requests per second** per account  When rate limits are exceeded, the API returns a `429 Too Many Requests` response with a `retry_after` header indicating when to retry.  ## Authentication The API supports two authentication methods: - **OAuth 2.0**: For web applications and integrations requiring user consent - **API Tokens**: For server-to-server integrations and personal access  ## Request Headers - **User-Agent**: Required header to identify the client application - **Content-Type**: Set to `application/json` for POST/PUT requests - **Authorization**: Bearer token or OAuth access token  ## Response Format All responses are in JSON format. List endpoints include pagination metadata in the `meta.pagination` object.  ## Error Handling The API uses standard HTTP status codes and includes detailed error messages in the response body for debugging. 
 *
 * The version of the OpenAPI document: 1.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EpicCreateRequestEpic
 */
export interface EpicCreateRequestEpic {
    /**
     * Name of the epic
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'name': string;
    /**
     * Description of the epic - may include HTML formatting
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'description'?: string;
    /**
     * Status of the epic - must be a valid status for the selected product
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'workflow_status'?: string;
    /**
     * Email address of the user who created the epic
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'created_by'?: string;
    /**
     * Email address of user that is assigned the epic
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'assigned_to_user'?: string;
    /**
     * Tags to add to the epic. Multiple tags must be separated by commas
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'tags'?: string;
    /**
     * The detailed estimated effort in time or story points for this epic
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'detailed_estimate_text'?: string;
    /**
     * The remaining estimated effort in time or story points for this epic
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'remaining_estimate_text'?: string;
    /**
     * Set the initial estimated effort in minutes or story points
     * @type {number}
     * @memberof EpicCreateRequestEpic
     */
    'initial_estimate'?: number;
    /**
     * Set the detailed estimated effort in minutes or story points
     * @type {number}
     * @memberof EpicCreateRequestEpic
     */
    'detailed_estimate'?: number;
    /**
     * Set the remaining estimated effort in minutes or story points
     * @type {number}
     * @memberof EpicCreateRequestEpic
     */
    'remaining_estimate'?: number;
    /**
     * Date that work will start on the epic in format YYYY-MM-DD
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'start_date'?: string;
    /**
     * Date that work is due to be completed on the epic in format YYYY-MM-DD
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'due_date'?: string;
    /**
     * Name or id of initiative which the epic belongs to
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'initiative'?: string;
    /**
     * Progress completed on the epic. May only be set when the progress_source is manual
     * @type {number}
     * @memberof EpicCreateRequestEpic
     */
    'progress'?: number;
    /**
     * Source for automatically calculating start and due dates
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'duration_source'?: EpicCreateRequestEpicDurationSourceEnum;
    /**
     * Numeric ID or key of the Develop team to assign the epic to
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'team'?: string;
    /**
     * Team status of the epic - must be a valid status for the selected team
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'team_workflow_status'?: string;
    /**
     * ID of sprint to assign the epic to, must belong to the selected team
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'iteration'?: string;
    /**
     * Numeric ID or key of the PI to assign the epic to
     * @type {string}
     * @memberof EpicCreateRequestEpic
     */
    'program_increment'?: string;
}

export const EpicCreateRequestEpicDurationSourceEnum = {
    DURATION_MANUAL: 'duration_manual',
    DURATION_FROM_FEATURES: 'duration_from_features'
} as const;

export type EpicCreateRequestEpicDurationSourceEnum = typeof EpicCreateRequestEpicDurationSourceEnum[keyof typeof EpicCreateRequestEpicDurationSourceEnum];


