/* tslint:disable */
/* eslint-disable */
/**
 * Aha! REST API
 * API for interacting with Aha! product management platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FeaturesIdTagsPutRequestFeature
 */
export interface FeaturesIdTagsPutRequestFeature {
    /**
     * Array of tags to set on the feature
     * @type {Array<string>}
     * @memberof FeaturesIdTagsPutRequestFeature
     */
    'tags'?: Array<string>;
}

