/* tslint:disable */
/* eslint-disable */
/**
 * Aha! REST API
 * API for interacting with Aha! product management platform.
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FeaturesIdEpicPutRequestFeature
 */
export interface FeaturesIdEpicPutRequestFeature {
    /**
     * Name or id of epic which the feature belongs to
     * @type {string}
     * @memberof FeaturesIdEpicPutRequestFeature
     */
    'epic'?: string;
}

