/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GoalsPostResponseGoalSuccessMetricDescription } from './goals-post-response-goal-success-metric-description';
// May contain unused imports in some cases
// @ts-ignore
import type { GoalsPostResponseGoalSuccessMetricWorkflowStatus } from './goals-post-response-goal-success-metric-workflow-status';

export interface GoalsPostResponseGoalSuccessMetric {
    'name'?: string;
    'description'?: GoalsPostResponseGoalSuccessMetricDescription;
    'workflow_status'?: GoalsPostResponseGoalSuccessMetricWorkflowStatus;
    'workflow_status_times'?: Array<string>;
}

