/* tslint:disable */
/* eslint-disable */
/**
 * Aha! REST API
 * API for interacting with Aha! product management platform.
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Goal } from './goal';
// May contain unused imports in some cases
// @ts-ignore
import type { GoalsListResponsePagination } from './goals-list-response-pagination';

/**
 * 
 * @export
 * @interface GoalsListResponse
 */
export interface GoalsListResponse {
    /**
     * 
     * @type {Array<Goal>}
     * @memberof GoalsListResponse
     */
    'goals'?: Array<Goal>;
    /**
     * 
     * @type {GoalsListResponsePagination}
     * @memberof GoalsListResponse
     */
    'pagination'?: GoalsListResponsePagination;
}

