/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EpicsPostResponseEpicProject } from './epics-post-response-epic-project';
// May contain unused imports in some cases
// @ts-ignore
import type { EpicsPostResponseEpicReleaseOwner } from './epics-post-response-epic-release-owner';
// May contain unused imports in some cases
// @ts-ignore
import type { GoalsPostResponseGoalDescription } from './goals-post-response-goal-description';
// May contain unused imports in some cases
// @ts-ignore
import type { GoalsPostResponseGoalSuccessMetric } from './goals-post-response-goal-success-metric';

export interface GoalsPostResponseGoal {
    'id'?: string;
    'name'?: string;
    'reference_num'?: string;
    'effort'?: number;
    'value'?: number;
    'color'?: string;
    'position'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'product_id'?: string;
    'progress'?: number;
    'progress_source'?: string;
    'url'?: string;
    'resource'?: string;
    'description'?: GoalsPostResponseGoalDescription;
    'success_metric'?: GoalsPostResponseGoalSuccessMetric;
    'project'?: EpicsPostResponseEpicProject;
    'initiatives'?: Array<any>;
    'key_results'?: Array<any>;
    'comments_count'?: number;
    'features'?: Array<any>;
    'releases'?: Array<any>;
    'custom_fields'?: Array<any>;
    'watchers'?: Array<EpicsPostResponseEpicReleaseOwner>;
}

