/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EpicsPostResponseEpicProject } from './epics-post-response-epic-project';
// May contain unused imports in some cases
// @ts-ignore
import type { EpicsPutResponseEpicFeaturesInner } from './epics-put-response-epic-features-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { FeaturesPutResponseFeatureKeyResultsInner } from './features-put-response-feature-key-results-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GoalsPutResponseGoalDescription } from './goals-put-response-goal-description';
// May contain unused imports in some cases
// @ts-ignore
import type { GoalsPutResponseGoalInitiativesInner } from './goals-put-response-goal-initiatives-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GoalsPutResponseGoalReleasesInner } from './goals-put-response-goal-releases-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { GoalsPutResponseGoalSuccessMetric } from './goals-put-response-goal-success-metric';
// May contain unused imports in some cases
// @ts-ignore
import type { Null } from './null';

export interface GoalsPutResponseGoal {
    'id'?: string;
    'name'?: string;
    'reference_num'?: string;
    'effort'?: number;
    'value'?: number;
    'color'?: string;
    'position'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'product_id'?: string;
    'progress'?: Null;
    'progress_source'?: string;
    'url'?: string;
    'resource'?: string;
    'description'?: GoalsPutResponseGoalDescription;
    'success_metric'?: GoalsPutResponseGoalSuccessMetric;
    'project'?: EpicsPostResponseEpicProject;
    'initiatives'?: Array<GoalsPutResponseGoalInitiativesInner>;
    'key_results'?: Array<FeaturesPutResponseFeatureKeyResultsInner>;
    'comments_count'?: number;
    'features'?: Array<EpicsPutResponseEpicFeaturesInner>;
    'releases'?: Array<GoalsPutResponseGoalReleasesInner>;
    'custom_fields'?: Array<any>;
}

