/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IdeacommentsPostResponseIdeaCommentIdea } from './ideacomments-post-response-idea-comment-idea';
// May contain unused imports in some cases
// @ts-ignore
import type { IdeavotesPutResponseIdeaEndorsementCustomFieldsInner } from './ideavotes-put-response-idea-endorsement-custom-fields-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { IdeavotesPutResponseIdeaEndorsementEndorsedByIdeaUser } from './ideavotes-put-response-idea-endorsement-endorsed-by-idea-user';
// May contain unused imports in some cases
// @ts-ignore
import type { IdeavotesPutResponseIdeaEndorsementEndorsedByPortalUser } from './ideavotes-put-response-idea-endorsement-endorsed-by-portal-user';
// May contain unused imports in some cases
// @ts-ignore
import type { IdeavotesPutResponseIdeaEndorsementIdeaOrganization } from './ideavotes-put-response-idea-endorsement-idea-organization';
// May contain unused imports in some cases
// @ts-ignore
import type { IdeavotesPutResponseIdeaEndorsementIntegrationFieldsInner } from './ideavotes-put-response-idea-endorsement-integration-fields-inner';

/**
 * 
 * @export
 * @interface IdeavotesPutResponseIdeaEndorsement
 */
export interface IdeavotesPutResponseIdeaEndorsement {
    /**
     * 
     * @type {string}
     * @memberof IdeavotesPutResponseIdeaEndorsement
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdeavotesPutResponseIdeaEndorsement
     */
    'idea_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdeavotesPutResponseIdeaEndorsement
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdeavotesPutResponseIdeaEndorsement
     */
    'updated_at'?: string;
    /**
     * 
     * @type {any}
     * @memberof IdeavotesPutResponseIdeaEndorsement
     */
    'value'?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IdeavotesPutResponseIdeaEndorsement
     */
    'link'?: any | null;
    /**
     * 
     * @type {number}
     * @memberof IdeavotesPutResponseIdeaEndorsement
     */
    'weight'?: number;
    /**
     * 
     * @type {IdeavotesPutResponseIdeaEndorsementEndorsedByPortalUser}
     * @memberof IdeavotesPutResponseIdeaEndorsement
     */
    'endorsed_by_portal_user'?: IdeavotesPutResponseIdeaEndorsementEndorsedByPortalUser;
    /**
     * 
     * @type {IdeavotesPutResponseIdeaEndorsementEndorsedByIdeaUser}
     * @memberof IdeavotesPutResponseIdeaEndorsement
     */
    'endorsed_by_idea_user'?: IdeavotesPutResponseIdeaEndorsementEndorsedByIdeaUser;
    /**
     * 
     * @type {IdeavotesPutResponseIdeaEndorsementIdeaOrganization}
     * @memberof IdeavotesPutResponseIdeaEndorsement
     */
    'idea_organization'?: IdeavotesPutResponseIdeaEndorsementIdeaOrganization;
    /**
     * 
     * @type {any}
     * @memberof IdeavotesPutResponseIdeaEndorsement
     */
    'description'?: any | null;
    /**
     * 
     * @type {Array<IdeavotesPutResponseIdeaEndorsementIntegrationFieldsInner>}
     * @memberof IdeavotesPutResponseIdeaEndorsement
     */
    'integration_fields'?: Array<IdeavotesPutResponseIdeaEndorsementIntegrationFieldsInner>;
    /**
     * 
     * @type {Array<IdeavotesPutResponseIdeaEndorsementCustomFieldsInner>}
     * @memberof IdeavotesPutResponseIdeaEndorsement
     */
    'custom_fields'?: Array<IdeavotesPutResponseIdeaEndorsementCustomFieldsInner>;
    /**
     * 
     * @type {IdeacommentsPostResponseIdeaCommentIdea}
     * @memberof IdeavotesPutResponseIdeaEndorsement
     */
    'idea'?: IdeacommentsPostResponseIdeaCommentIdea;
}

