/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IdeacommentsPostResponseIdeaCommentIdea } from './ideacomments-post-response-idea-comment-idea';
// May contain unused imports in some cases
// @ts-ignore
import type { IdeasubscriptionsPostResponseIdeaSubscriptionPortalUser } from './ideasubscriptions-post-response-idea-subscription-portal-user';

/**
 * 
 * @export
 * @interface IdeasubscriptionsPostResponseIdeaSubscription
 */
export interface IdeasubscriptionsPostResponseIdeaSubscription {
    /**
     * 
     * @type {string}
     * @memberof IdeasubscriptionsPostResponseIdeaSubscription
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdeasubscriptionsPostResponseIdeaSubscription
     */
    'idea_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdeasubscriptionsPostResponseIdeaSubscription
     */
    'created_at'?: string;
    /**
     * 
     * @type {IdeasubscriptionsPostResponseIdeaSubscriptionPortalUser}
     * @memberof IdeasubscriptionsPostResponseIdeaSubscription
     */
    'portal_user'?: IdeasubscriptionsPostResponseIdeaSubscriptionPortalUser;
    /**
     * 
     * @type {IdeacommentsPostResponseIdeaCommentIdea}
     * @memberof IdeasubscriptionsPostResponseIdeaSubscription
     */
    'idea'?: IdeacommentsPostResponseIdeaCommentIdea;
}

