/* tslint:disable */
/* eslint-disable */
/**
 * Aha! REST API
 * API for interacting with Aha! product management platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IdeasGetVotes200ResponsePagination } from './ideas-get-votes200-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import type { IdeasGetVotes200ResponseVotesInner } from './ideas-get-votes200-response-votes-inner';

/**
 * 
 * @export
 * @interface IdeasGetVotes200Response
 */
export interface IdeasGetVotes200Response {
    /**
     * 
     * @type {Array<IdeasGetVotes200ResponseVotesInner>}
     * @memberof IdeasGetVotes200Response
     */
    'votes'?: Array<IdeasGetVotes200ResponseVotesInner>;
    /**
     * 
     * @type {IdeasGetVotes200ResponsePagination}
     * @memberof IdeasGetVotes200Response
     */
    'pagination'?: IdeasGetVotes200ResponsePagination;
}

