/* tslint:disable */
/* eslint-disable */
/**
 * Aha! REST API
 * API for interacting with Aha! product management platform.
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IdeaOrganizationCreateRequest
 */
export interface IdeaOrganizationCreateRequest {
    /**
     * Name of the idea organization
     * @type {string}
     * @memberof IdeaOrganizationCreateRequest
     */
    'name': string;
    /**
     * Email domains associated with the organization
     * @type {Array<string>}
     * @memberof IdeaOrganizationCreateRequest
     */
    'email_domains'?: Array<string>;
    /**
     * Revenue value for the organization
     * @type {number}
     * @memberof IdeaOrganizationCreateRequest
     */
    'revenue'?: number;
    /**
     * Custom fields for the organization
     * @type {{ [key: string]: any; }}
     * @memberof IdeaOrganizationCreateRequest
     */
    'custom_fields'?: { [key: string]: any; };
}

