/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IdeaPortalsPostRequest
 */
export interface IdeaPortalsPostRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof IdeaPortalsPostRequest
     */
    'idea_portal_ids'?: Array<string>;
}

