/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IdeaorganizationsPutRequestIdeaOrganization
 */
export interface IdeaorganizationsPutRequestIdeaOrganization {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof IdeaorganizationsPutRequestIdeaOrganization
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdeaorganizationsPutRequestIdeaOrganization
     */
    'email_domains'?: string;
    /**
     * 
     * @type {string}
     * @memberof IdeaorganizationsPutRequestIdeaOrganization
     */
    'revenue'?: string;
    /**
     * Custom table records to link, keyed by many-to-many custom field name. Replaces the existing list.
     * @type {{ [key: string]: Array<string>; }}
     * @memberof IdeaorganizationsPutRequestIdeaOrganization
     */
    'custom_object_links'?: { [key: string]: Array<string>; };
}

