/* tslint:disable */
/* eslint-disable */
/**
 * Aha! REST API
 * API for interacting with Aha! product management platform.
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Time frame for this initiative
 * @export
 * @interface InitiativeCreateRequestInitiativeTimeFrame
 */
export interface InitiativeCreateRequestInitiativeTimeFrame {
    /**
     * ID of the time frame
     * @type {number}
     * @memberof InitiativeCreateRequestInitiativeTimeFrame
     */
    'id'?: number;
    /**
     * Name of the time frame
     * @type {string}
     * @memberof InitiativeCreateRequestInitiativeTimeFrame
     */
    'name'?: string;
}

