/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EpicsPostResponseEpicReleaseProject } from './epics-post-response-epic-release-project';
// May contain unused imports in some cases
// @ts-ignore
import type { InitiativesGetResponseInitiativesInnerAssignedToUser } from './initiatives-get-response-initiatives-inner-assigned-to-user';
// May contain unused imports in some cases
// @ts-ignore
import type { InitiativesGetResponseInitiativesInnerCreatedByUser } from './initiatives-get-response-initiatives-inner-created-by-user';
// May contain unused imports in some cases
// @ts-ignore
import type { InitiativesGetResponseInitiativesInnerDescription } from './initiatives-get-response-initiatives-inner-description';
// May contain unused imports in some cases
// @ts-ignore
import type { InitiativesGetResponseInitiativesInnerWorkflowStatus } from './initiatives-get-response-initiatives-inner-workflow-status';
// May contain unused imports in some cases
// @ts-ignore
import type { Null } from './null';

export interface InitiativesGetResponseInitiativesInner {
    'id'?: string;
    'name'?: string;
    'reference_num'?: string;
    'status'?: string;
    'effort'?: number;
    'value'?: number;
    'presented'?: boolean;
    'color'?: string;
    'start_date'?: Null;
    'end_date'?: Null;
    'position'?: number;
    'score'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'product_id'?: string;
    'progress'?: Null;
    'progress_source'?: string;
    'duration_source'?: string;
    'url'?: string;
    'resource'?: string;
    'project'?: EpicsPostResponseEpicReleaseProject;
    'workflow_status'?: InitiativesGetResponseInitiativesInnerWorkflowStatus;
    'description'?: InitiativesGetResponseInitiativesInnerDescription;
    'attachments'?: Array<any>;
    'assigned_to_user'?: InitiativesGetResponseInitiativesInnerAssignedToUser;
    'comments_count'?: number;
    'goals'?: Array<any>;
    'key_results'?: Array<any>;
    'score_facts'?: Array<any>;
    'integration_fields'?: Array<any>;
    'created_by_user'?: InitiativesGetResponseInitiativesInnerCreatedByUser;
}

