/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IntegrationfieldsPostResponseIntegrationFieldIntegratable } from './integrationfields-post-response-integration-field-integratable';

/**
 * 
 * @export
 * @interface IntegrationfieldsPostResponseIntegrationField
 */
export interface IntegrationfieldsPostResponseIntegrationField {
    /**
     * 
     * @type {string}
     * @memberof IntegrationfieldsPostResponseIntegrationField
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationfieldsPostResponseIntegrationField
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationfieldsPostResponseIntegrationField
     */
    'value'?: string;
    /**
     * 
     * @type {number}
     * @memberof IntegrationfieldsPostResponseIntegrationField
     */
    'integration_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof IntegrationfieldsPostResponseIntegrationField
     */
    'service_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationfieldsPostResponseIntegrationField
     */
    'created_at'?: string;
    /**
     * 
     * @type {IntegrationfieldsPostResponseIntegrationFieldIntegratable}
     * @memberof IntegrationfieldsPostResponseIntegrationField
     */
    'integratable'?: IntegrationfieldsPostResponseIntegrationFieldIntegratable;
}

