/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NotesGetResponsePagesInner
 */
export interface NotesGetResponsePagesInner {
    /**
     * 
     * @type {string}
     * @memberof NotesGetResponsePagesInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotesGetResponsePagesInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotesGetResponsePagesInner
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotesGetResponsePagesInner
     */
    'created_at'?: string;
    /**
     * 
     * @type {any}
     * @memberof NotesGetResponsePagesInner
     */
    'parent_id'?: any | null;
    /**
     * 
     * @type {string}
     * @memberof NotesGetResponsePagesInner
     */
    'reference_num'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotesGetResponsePagesInner
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof NotesGetResponsePagesInner
     */
    'resource'?: string;
}

