/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PersonasPostResponsePersona
 */
export interface PersonasPostResponsePersona {
    /**
     * 
     * @type {string}
     * @memberof PersonasPostResponsePersona
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonasPostResponsePersona
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonasPostResponsePersona
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonasPostResponsePersona
     */
    'reference_num'?: string;
    /**
     * 
     * @type {number}
     * @memberof PersonasPostResponsePersona
     */
    'color'?: number;
    /**
     * 
     * @type {any}
     * @memberof PersonasPostResponsePersona
     */
    'occupation'?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PersonasPostResponsePersona
     */
    'quote'?: any | null;
    /**
     * 
     * @type {string}
     * @memberof PersonasPostResponsePersona
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonasPostResponsePersona
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonasPostResponsePersona
     */
    'resource'?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof PersonasPostResponsePersona
     */
    'custom_fields'?: Array<any>;
    /**
     * 
     * @type {number}
     * @memberof PersonasPostResponsePersona
     */
    'comments_count'?: number;
}

