/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReleasephasesPutResponseReleasePhaseDescription
 */
export interface ReleasephasesPutResponseReleasePhaseDescription {
    /**
     * 
     * @type {string}
     * @memberof ReleasephasesPutResponseReleasePhaseDescription
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasephasesPutResponseReleasePhaseDescription
     */
    'body'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasephasesPutResponseReleasePhaseDescription
     */
    'notable_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasephasesPutResponseReleasePhaseDescription
     */
    'notable_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof ReleasephasesPutResponseReleasePhaseDescription
     */
    'editor_version'?: number;
    /**
     * 
     * @type {string}
     * @memberof ReleasephasesPutResponseReleasePhaseDescription
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasephasesPutResponseReleasePhaseDescription
     */
    'updated_at'?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof ReleasephasesPutResponseReleasePhaseDescription
     */
    'attachments'?: Array<any>;
}

