/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReleasesPutResponseReleaseIntegrationFieldsInner
 */
export interface ReleasesPutResponseReleaseIntegrationFieldsInner {
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseReleaseIntegrationFieldsInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseReleaseIntegrationFieldsInner
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseReleaseIntegrationFieldsInner
     */
    'value'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseReleaseIntegrationFieldsInner
     */
    'integration_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseReleaseIntegrationFieldsInner
     */
    'service_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseReleaseIntegrationFieldsInner
     */
    'created_at'?: string;
}

