/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EpicsPostResponseEpicProject } from './epics-post-response-epic-project';
// May contain unused imports in some cases
// @ts-ignore
import type { EpicsPutResponseEpicCreatedByUser } from './epics-put-response-epic-created-by-user';
// May contain unused imports in some cases
// @ts-ignore
import type { EpicsPutResponseEpicGoalsInner } from './epics-put-response-epic-goals-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ReleasesPutResponseReleaseCustomFieldsInner } from './releases-put-response-release-custom-fields-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ReleasesPutResponseReleaseIntegrationFieldsInner } from './releases-put-response-release-integration-fields-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { ReleasesPutResponseReleaseTheme } from './releases-put-response-release-theme';
// May contain unused imports in some cases
// @ts-ignore
import type { ReleasesPutResponseReleaseWorkflowStatus } from './releases-put-response-release-workflow-status';

/**
 * 
 * @export
 * @interface ReleasesPutResponseRelease
 */
export interface ReleasesPutResponseRelease {
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'product_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'reference_num'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'start_date'?: string;
    /**
     * 
     * @type {any}
     * @memberof ReleasesPutResponseRelease
     */
    'end_date'?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'development_started_on'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'release_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'external_release_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'external_release_date_description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'external_date_resolution'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReleasesPutResponseRelease
     */
    'released'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReleasesPutResponseRelease
     */
    'parking_lot'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ReleasesPutResponseRelease
     */
    'master_release'?: boolean;
    /**
     * 
     * @type {any}
     * @memberof ReleasesPutResponseRelease
     */
    'released_on'?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'updated_at'?: string;
    /**
     * 
     * @type {any}
     * @memberof ReleasesPutResponseRelease
     */
    'position'?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ReleasesPutResponseRelease
     */
    'progress'?: any | null;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'progress_source'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'duration_source'?: string;
    /**
     * 
     * @type {any}
     * @memberof ReleasesPutResponseRelease
     */
    'status_changed_on'?: any | null;
    /**
     * 
     * @type {ReleasesPutResponseReleaseTheme}
     * @memberof ReleasesPutResponseRelease
     */
    'theme'?: ReleasesPutResponseReleaseTheme;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesPutResponseRelease
     */
    'resource'?: string;
    /**
     * 
     * @type {Array<ReleasesPutResponseReleaseIntegrationFieldsInner>}
     * @memberof ReleasesPutResponseRelease
     */
    'integration_fields'?: Array<ReleasesPutResponseReleaseIntegrationFieldsInner>;
    /**
     * 
     * @type {Array<ReleasesPutResponseReleaseCustomFieldsInner>}
     * @memberof ReleasesPutResponseRelease
     */
    'custom_fields'?: Array<ReleasesPutResponseReleaseCustomFieldsInner>;
    /**
     * 
     * @type {number}
     * @memberof ReleasesPutResponseRelease
     */
    'comments_count'?: number;
    /**
     * 
     * @type {ReleasesPutResponseReleaseWorkflowStatus}
     * @memberof ReleasesPutResponseRelease
     */
    'workflow_status'?: ReleasesPutResponseReleaseWorkflowStatus;
    /**
     * 
     * @type {EpicsPutResponseEpicCreatedByUser}
     * @memberof ReleasesPutResponseRelease
     */
    'owner'?: EpicsPutResponseEpicCreatedByUser;
    /**
     * 
     * @type {Array<EpicsPutResponseEpicGoalsInner>}
     * @memberof ReleasesPutResponseRelease
     */
    'goals'?: Array<EpicsPutResponseEpicGoalsInner>;
    /**
     * 
     * @type {Array<any>}
     * @memberof ReleasesPutResponseRelease
     */
    'key_results'?: Array<any>;
    /**
     * 
     * @type {EpicsPostResponseEpicProject}
     * @memberof ReleasesPutResponseRelease
     */
    'project'?: EpicsPostResponseEpicProject;
    /**
     * 
     * @type {EpicsPutResponseEpicCreatedByUser}
     * @memberof ReleasesPutResponseRelease
     */
    'created_by_user'?: EpicsPutResponseEpicCreatedByUser;
}

