/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReleasesGetResponseReleasesInnerProject
 */
export interface ReleasesGetResponseReleasesInnerProject {
    /**
     * 
     * @type {string}
     * @memberof ReleasesGetResponseReleasesInnerProject
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesGetResponseReleasesInnerProject
     */
    'reference_prefix'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesGetResponseReleasesInnerProject
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesGetResponseReleasesInnerProject
     */
    'product_line'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesGetResponseReleasesInnerProject
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesGetResponseReleasesInnerProject
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleasesGetResponseReleasesInnerProject
     */
    'workspace_type'?: string;
}

