/* tslint:disable */
/* eslint-disable */
/**
 * Aha! REST API
 * API for interacting with Aha! product management platform.
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RequirementFullTagsInner
 */
export interface RequirementFullTagsInner {
    /**
     * ID of the tag
     * @type {string}
     * @memberof RequirementFullTagsInner
     */
    'id'?: string;
    /**
     * Name of the tag
     * @type {string}
     * @memberof RequirementFullTagsInner
     */
    'name'?: string;
}

