/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CommentsPostResponseCommentUser } from './comments-post-response-comment-user';
// May contain unused imports in some cases
// @ts-ignore
import type { CustomtablerecordlinksPutResponseRequirementAssignedToUser } from './customtablerecordlinks-put-response-requirement-assigned-to-user';
// May contain unused imports in some cases
// @ts-ignore
import type { CustomtablerecordlinksPutResponseRequirementWorkflowStatus } from './customtablerecordlinks-put-response-requirement-workflow-status';
// May contain unused imports in some cases
// @ts-ignore
import type { EpicsPostResponseEpicProject } from './epics-post-response-epic-project';
// May contain unused imports in some cases
// @ts-ignore
import type { EpicsPostResponseEpicRelease } from './epics-post-response-epic-release';
// May contain unused imports in some cases
// @ts-ignore
import type { EpicsPostResponseEpicWorkflowStatusTimesInner } from './epics-post-response-epic-workflow-status-times-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { FeaturesPostResponseFeatureWorkflowKind } from './features-post-response-feature-workflow-kind';
// May contain unused imports in some cases
// @ts-ignore
import type { Null } from './null';
// May contain unused imports in some cases
// @ts-ignore
import type { RequirementsPostResponseFeatureCustomFieldsInner } from './requirements-post-response-feature-custom-fields-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { RequirementsPostResponseFeatureDescription } from './requirements-post-response-feature-description';
// May contain unused imports in some cases
// @ts-ignore
import type { RequirementsPostResponseFeatureFeatureLinksInner } from './requirements-post-response-feature-feature-links-inner';

export interface RequirementsPostResponseFeature {
    'id'?: string;
    'name'?: string;
    'reference_num'?: string;
    'initiative_reference_num'?: Null;
    'release_reference_num'?: string;
    'epic_reference_num'?: Null;
    'position'?: number;
    'score'?: number;
    'created_at'?: string;
    'updated_at'?: string;
    'start_date'?: Null;
    'due_date'?: Null;
    'product_id'?: string;
    'progress'?: number;
    'progress_source'?: string;
    'status_changed_on'?: string;
    'created_by_user'?: CommentsPostResponseCommentUser;
    'workflow_kind'?: FeaturesPostResponseFeatureWorkflowKind;
    'workflow_status'?: CustomtablerecordlinksPutResponseRequirementWorkflowStatus;
    'project'?: EpicsPostResponseEpicProject;
    'description'?: RequirementsPostResponseFeatureDescription;
    'attachments'?: Array<any>;
    'integration_fields'?: Array<any>;
    'url'?: string;
    'resource'?: string;
    'release'?: EpicsPostResponseEpicRelease;
    'assigned_to_user'?: CustomtablerecordlinksPutResponseRequirementAssignedToUser;
    'requirements'?: Array<any>;
    'goals'?: Array<any>;
    'comments_count'?: number;
    'score_facts'?: Array<any>;
    'tags'?: Array<any>;
    'full_tags'?: Array<any>;
    'custom_fields'?: Array<RequirementsPostResponseFeatureCustomFieldsInner>;
    'feature_links'?: Array<RequirementsPostResponseFeatureFeatureLinksInner>;
    'workflow_status_times'?: Array<EpicsPostResponseEpicWorkflowStatusTimesInner>;
    'feature_only_original_estimate'?: Null;
    'feature_only_remaining_estimate'?: Null;
    'feature_only_work_done'?: Null;
}

