/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface StrategicmodelsGetResponseStrategyModelProject {
    'id'?: string;
    'reference_prefix'?: string;
    'name'?: string;
    'product_line'?: boolean;
    'created_at'?: string;
    'url'?: string;
    'workspace_type'?: string;
}

