/* tslint:disable */
/* eslint-disable */
/**
 * Aha! REST API
 * API for interacting with Aha! product management platform.
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { InitiativeResponseInitiativeProject } from './initiative-response-initiative-project';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

/**
 * 
 * @export
 * @interface StrategicModel
 */
export interface StrategicModel {
    /**
     * Unique identifier of the strategic model
     * @type {string}
     * @memberof StrategicModel
     */
    'id'?: string;
    /**
     * Name of the strategic model
     * @type {string}
     * @memberof StrategicModel
     */
    'name'?: string;
    /**
     * Description of the strategic model
     * @type {string}
     * @memberof StrategicModel
     */
    'description'?: string;
    /**
     * Type of strategic model
     * @type {string}
     * @memberof StrategicModel
     */
    'type'?: StrategicModelTypeEnum;
    /**
     * Creation date of the strategic model
     * @type {string}
     * @memberof StrategicModel
     */
    'created_at'?: string;
    /**
     * Last update date of the strategic model
     * @type {string}
     * @memberof StrategicModel
     */
    'updated_at'?: string;
    /**
     * 
     * @type {User}
     * @memberof StrategicModel
     */
    'created_by_user'?: User;
    /**
     * URL to view the strategic model in the Aha! web application
     * @type {string}
     * @memberof StrategicModel
     */
    'url'?: string;
    /**
     * API resource URL for the strategic model
     * @type {string}
     * @memberof StrategicModel
     */
    'resource'?: string;
    /**
     * 
     * @type {InitiativeResponseInitiativeProject}
     * @memberof StrategicModel
     */
    'project'?: InitiativeResponseInitiativeProject;
    /**
     * Strategic model data structure (varies by type)
     * @type {{ [key: string]: any; }}
     * @memberof StrategicModel
     */
    'data'?: { [key: string]: any; };
    /**
     * Attachments to the strategic model
     * @type {Array<object>}
     * @memberof StrategicModel
     */
    'attachments'?: Array<object>;
    /**
     * Tags associated with the strategic model
     * @type {Array<string>}
     * @memberof StrategicModel
     */
    'tags'?: Array<string>;
    /**
     * Full tag objects with metadata
     * @type {Array<object>}
     * @memberof StrategicModel
     */
    'full_tags'?: Array<object>;
}

export const StrategicModelTypeEnum = {
    SWOT: 'swot',
    PORTER_FIVE_FORCES: 'porter_five_forces',
    ANSOFF_MATRIX: 'ansoff_matrix',
    VALUE_PROPOSITION_CANVAS: 'value_proposition_canvas',
    BUSINESS_MODEL_CANVAS: 'business_model_canvas',
    LEAN_CANVAS: 'lean_canvas',
    CUSTOM: 'custom'
} as const;

export type StrategicModelTypeEnum = typeof StrategicModelTypeEnum[keyof typeof StrategicModelTypeEnum];


