/* tslint:disable */
/* eslint-disable */
/**
 * Aha! REST API
 * API for interacting with Aha! product management platform.
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StrategicModelCreateRequest
 */
export interface StrategicModelCreateRequest {
    /**
     * Name of the strategic model
     * @type {string}
     * @memberof StrategicModelCreateRequest
     */
    'name': string;
    /**
     * Description of the strategic model
     * @type {string}
     * @memberof StrategicModelCreateRequest
     */
    'description'?: string;
    /**
     * Type of strategic model
     * @type {string}
     * @memberof StrategicModelCreateRequest
     */
    'type': StrategicModelCreateRequestTypeEnum;
    /**
     * Strategic model data structure (varies by type)
     * @type {object}
     * @memberof StrategicModelCreateRequest
     */
    'data'?: object;
    /**
     * Tags to associate with the strategic model
     * @type {Array<string>}
     * @memberof StrategicModelCreateRequest
     */
    'tags'?: Array<string>;
}

export const StrategicModelCreateRequestTypeEnum = {
    SWOT: 'swot',
    PORTER_FIVE_FORCES: 'porter_five_forces',
    ANSOFF_MATRIX: 'ansoff_matrix',
    VALUE_PROPOSITION_CANVAS: 'value_proposition_canvas',
    BUSINESS_MODEL_CANVAS: 'business_model_canvas',
    LEAN_CANVAS: 'lean_canvas',
    CUSTOM: 'custom'
} as const;

export type StrategicModelCreateRequestTypeEnum = typeof StrategicModelCreateRequestTypeEnum[keyof typeof StrategicModelCreateRequestTypeEnum];


