/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AssistantusageGetResponsePagination } from './assistantusage-get-response-pagination';
// May contain unused imports in some cases
// @ts-ignore
import type { TeammembershipsGetResponseTeamMembershipsInner } from './teammemberships-get-response-team-memberships-inner';

/**
 * 
 * @export
 * @interface TeammembershipsGetResponse
 */
export interface TeammembershipsGetResponse {
    /**
     * 
     * @type {Array<TeammembershipsGetResponseTeamMembershipsInner>}
     * @memberof TeammembershipsGetResponse
     */
    'team_memberships'?: Array<TeammembershipsGetResponseTeamMembershipsInner>;
    /**
     * 
     * @type {AssistantusageGetResponsePagination}
     * @memberof TeammembershipsGetResponse
     */
    'pagination'?: AssistantusageGetResponsePagination;
}

