/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UsersPutResponseAdministratorRoles } from './users-put-response-administrator-roles';
// May contain unused imports in some cases
// @ts-ignore
import type { UsersPutResponseIdentityProvider } from './users-put-response-identity-provider';
// May contain unused imports in some cases
// @ts-ignore
import type { UsersPutResponseProductRolesInner } from './users-put-response-product-roles-inner';

/**
 * 
 * @export
 * @interface UsersPutResponse
 */
export interface UsersPutResponse {
    /**
     * 
     * @type {string}
     * @memberof UsersPutResponse
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPutResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPutResponse
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPutResponse
     */
    'timezone'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPutResponse
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPutResponse
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof UsersPutResponse
     */
    'accessed_at'?: string;
    /**
     * 
     * @type {Array<UsersPutResponseProductRolesInner>}
     * @memberof UsersPutResponse
     */
    'product_roles'?: Array<UsersPutResponseProductRolesInner>;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPutResponse
     */
    'enabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPutResponse
     */
    'paid_seat'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UsersPutResponse
     */
    'administrator'?: boolean;
    /**
     * 
     * @type {UsersPutResponseAdministratorRoles}
     * @memberof UsersPutResponse
     */
    'administrator_roles'?: UsersPutResponseAdministratorRoles;
    /**
     * 
     * @type {UsersPutResponseIdentityProvider}
     * @memberof UsersPutResponse
     */
    'identity_provider'?: UsersPutResponseIdentityProvider;
}

