/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IdeacommentsPostResponseIdeaCommentIdeaWorkflowStatus } from './ideacomments-post-response-idea-comment-idea-workflow-status';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowsGetResponseWorkflowWorkflowKindsInner } from './workflows-get-response-workflow-workflow-kinds-inner';

export interface WorkflowsGetResponseWorkflow {
    'id'?: number;
    'name'?: string;
    'statusable_type'?: string;
    'transitions_only'?: boolean;
    'workflow_statuses'?: Array<IdeacommentsPostResponseIdeaCommentIdeaWorkflowStatus>;
    'workflow_kinds'?: Array<WorkflowsGetResponseWorkflowWorkflowKindsInner>;
}

