/* tslint:disable */
/* eslint-disable */
/**
 * Aha! REST API
 * API for interacting with Aha! product management platform.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EpicWorkflowStatus
 */
export interface EpicWorkflowStatus {
    /**
     * 
     * @type {string}
     * @memberof EpicWorkflowStatus
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof EpicWorkflowStatus
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof EpicWorkflowStatus
     */
    'position'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EpicWorkflowStatus
     */
    'complete'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EpicWorkflowStatus
     */
    'color'?: string;
}

