/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ReleasephasesGetResponse } from '../model';
// @ts-ignore
import type { ReleasephasesPostRequest } from '../model';
// @ts-ignore
import type { ReleasephasesPostResponse } from '../model';
// @ts-ignore
import type { ReleasephasesPutResponse } from '../model';
/**
 * ReleasePhasesApi - axios parameter creator
 * @export
 */
export const ReleasePhasesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete a release phase
         * @param {string} id Id identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releasePhasesByIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('releasePhasesByIdDelete', 'id', id)
            const localVarPath = `/release_phases/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a specific release phase
         * @param {string} id Id identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releasePhasesByIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('releasePhasesByIdGet', 'id', id)
            const localVarPath = `/release_phases/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a release phase
         * @param {string} id Id identifier
         * @param {ReleasephasesPostRequest} releasephasesPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releasePhasesByIdPut: async (id: string, releasephasesPostRequest: ReleasephasesPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('releasePhasesByIdPut', 'id', id)
            // verify required parameter 'releasephasesPostRequest' is not null or undefined
            assertParamExists('releasePhasesByIdPut', 'releasephasesPostRequest', releasephasesPostRequest)
            const localVarPath = `/release_phases/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(releasephasesPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List release phases in the account
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releasePhasesGet: async (page?: string, perPage?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/release_phases`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a release milestone
         * @param {ReleasephasesPostRequest} releasephasesPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releasePhasesPost: async (releasephasesPostRequest: ReleasephasesPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'releasephasesPostRequest' is not null or undefined
            assertParamExists('releasePhasesPost', 'releasephasesPostRequest', releasephasesPostRequest)
            const localVarPath = `/release_phases`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(releasephasesPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List release phases for a release
         * @param {string} id Id identifier
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releasesByIdReleasePhasesGet: async (id: string, page?: string, perPage?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('releasesByIdReleasePhasesGet', 'id', id)
            const localVarPath = `/releases/{id}/release_phases`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReleasePhasesApi - functional programming interface
 * @export
 */
export const ReleasePhasesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReleasePhasesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Delete a release phase
         * @param {string} id Id identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async releasePhasesByIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.releasePhasesByIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePhasesApi.releasePhasesByIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a specific release phase
         * @param {string} id Id identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async releasePhasesByIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReleasephasesGetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.releasePhasesByIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePhasesApi.releasePhasesByIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a release phase
         * @param {string} id Id identifier
         * @param {ReleasephasesPostRequest} releasephasesPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async releasePhasesByIdPut(id: string, releasephasesPostRequest: ReleasephasesPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReleasephasesPutResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.releasePhasesByIdPut(id, releasephasesPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePhasesApi.releasePhasesByIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List release phases in the account
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async releasePhasesGet(page?: string, perPage?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReleasephasesGetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.releasePhasesGet(page, perPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePhasesApi.releasePhasesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a release milestone
         * @param {ReleasephasesPostRequest} releasephasesPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async releasePhasesPost(releasephasesPostRequest: ReleasephasesPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReleasephasesPostResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.releasePhasesPost(releasephasesPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePhasesApi.releasePhasesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List release phases for a release
         * @param {string} id Id identifier
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async releasesByIdReleasePhasesGet(id: string, page?: string, perPage?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReleasephasesGetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.releasesByIdReleasePhasesGet(id, page, perPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReleasePhasesApi.releasesByIdReleasePhasesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReleasePhasesApi - factory interface
 * @export
 */
export const ReleasePhasesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReleasePhasesApiFp(configuration)
    return {
        /**
         * 
         * @summary Delete a release phase
         * @param {ReleasePhasesApiReleasePhasesByIdDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releasePhasesByIdDelete(requestParameters: ReleasePhasesApiReleasePhasesByIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.releasePhasesByIdDelete(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a specific release phase
         * @param {ReleasePhasesApiReleasePhasesByIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releasePhasesByIdGet(requestParameters: ReleasePhasesApiReleasePhasesByIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReleasephasesGetResponse> {
            return localVarFp.releasePhasesByIdGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a release phase
         * @param {ReleasePhasesApiReleasePhasesByIdPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releasePhasesByIdPut(requestParameters: ReleasePhasesApiReleasePhasesByIdPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReleasephasesPutResponse> {
            return localVarFp.releasePhasesByIdPut(requestParameters.id, requestParameters.releasephasesPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List release phases in the account
         * @param {ReleasePhasesApiReleasePhasesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releasePhasesGet(requestParameters: ReleasePhasesApiReleasePhasesGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ReleasephasesGetResponse> {
            return localVarFp.releasePhasesGet(requestParameters.page, requestParameters.perPage, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a release milestone
         * @param {ReleasePhasesApiReleasePhasesPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releasePhasesPost(requestParameters: ReleasePhasesApiReleasePhasesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReleasephasesPostResponse> {
            return localVarFp.releasePhasesPost(requestParameters.releasephasesPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List release phases for a release
         * @param {ReleasePhasesApiReleasesByIdReleasePhasesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        releasesByIdReleasePhasesGet(requestParameters: ReleasePhasesApiReleasesByIdReleasePhasesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReleasephasesGetResponse> {
            return localVarFp.releasesByIdReleasePhasesGet(requestParameters.id, requestParameters.page, requestParameters.perPage, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReleasePhasesApi - interface
 * @export
 * @interface ReleasePhasesApi
 */
export interface ReleasePhasesApiInterface {
    /**
     * 
     * @summary Delete a release phase
     * @param {ReleasePhasesApiReleasePhasesByIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleasePhasesApiInterface
     */
    releasePhasesByIdDelete(requestParameters: ReleasePhasesApiReleasePhasesByIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get a specific release phase
     * @param {ReleasePhasesApiReleasePhasesByIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleasePhasesApiInterface
     */
    releasePhasesByIdGet(requestParameters: ReleasePhasesApiReleasePhasesByIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReleasephasesGetResponse>;

    /**
     * 
     * @summary Update a release phase
     * @param {ReleasePhasesApiReleasePhasesByIdPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleasePhasesApiInterface
     */
    releasePhasesByIdPut(requestParameters: ReleasePhasesApiReleasePhasesByIdPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReleasephasesPutResponse>;

    /**
     * 
     * @summary List release phases in the account
     * @param {ReleasePhasesApiReleasePhasesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleasePhasesApiInterface
     */
    releasePhasesGet(requestParameters?: ReleasePhasesApiReleasePhasesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReleasephasesGetResponse>;

    /**
     * 
     * @summary Create a release milestone
     * @param {ReleasePhasesApiReleasePhasesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleasePhasesApiInterface
     */
    releasePhasesPost(requestParameters: ReleasePhasesApiReleasePhasesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReleasephasesPostResponse>;

    /**
     * 
     * @summary List release phases for a release
     * @param {ReleasePhasesApiReleasesByIdReleasePhasesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleasePhasesApiInterface
     */
    releasesByIdReleasePhasesGet(requestParameters: ReleasePhasesApiReleasesByIdReleasePhasesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<ReleasephasesGetResponse>;

}

/**
 * Request parameters for releasePhasesByIdDelete operation in ReleasePhasesApi.
 * @export
 * @interface ReleasePhasesApiReleasePhasesByIdDeleteRequest
 */
export interface ReleasePhasesApiReleasePhasesByIdDeleteRequest {
    /**
     * Id identifier
     * @type {string}
     * @memberof ReleasePhasesApiReleasePhasesByIdDelete
     */
    readonly id: string
}

/**
 * Request parameters for releasePhasesByIdGet operation in ReleasePhasesApi.
 * @export
 * @interface ReleasePhasesApiReleasePhasesByIdGetRequest
 */
export interface ReleasePhasesApiReleasePhasesByIdGetRequest {
    /**
     * Id identifier
     * @type {string}
     * @memberof ReleasePhasesApiReleasePhasesByIdGet
     */
    readonly id: string
}

/**
 * Request parameters for releasePhasesByIdPut operation in ReleasePhasesApi.
 * @export
 * @interface ReleasePhasesApiReleasePhasesByIdPutRequest
 */
export interface ReleasePhasesApiReleasePhasesByIdPutRequest {
    /**
     * Id identifier
     * @type {string}
     * @memberof ReleasePhasesApiReleasePhasesByIdPut
     */
    readonly id: string

    /**
     * 
     * @type {ReleasephasesPostRequest}
     * @memberof ReleasePhasesApiReleasePhasesByIdPut
     */
    readonly releasephasesPostRequest: ReleasephasesPostRequest
}

/**
 * Request parameters for releasePhasesGet operation in ReleasePhasesApi.
 * @export
 * @interface ReleasePhasesApiReleasePhasesGetRequest
 */
export interface ReleasePhasesApiReleasePhasesGetRequest {
    /**
     * 
     * @type {string}
     * @memberof ReleasePhasesApiReleasePhasesGet
     */
    readonly page?: string

    /**
     * 
     * @type {string}
     * @memberof ReleasePhasesApiReleasePhasesGet
     */
    readonly perPage?: string
}

/**
 * Request parameters for releasePhasesPost operation in ReleasePhasesApi.
 * @export
 * @interface ReleasePhasesApiReleasePhasesPostRequest
 */
export interface ReleasePhasesApiReleasePhasesPostRequest {
    /**
     * 
     * @type {ReleasephasesPostRequest}
     * @memberof ReleasePhasesApiReleasePhasesPost
     */
    readonly releasephasesPostRequest: ReleasephasesPostRequest
}

/**
 * Request parameters for releasesByIdReleasePhasesGet operation in ReleasePhasesApi.
 * @export
 * @interface ReleasePhasesApiReleasesByIdReleasePhasesGetRequest
 */
export interface ReleasePhasesApiReleasesByIdReleasePhasesGetRequest {
    /**
     * Id identifier
     * @type {string}
     * @memberof ReleasePhasesApiReleasesByIdReleasePhasesGet
     */
    readonly id: string

    /**
     * 
     * @type {string}
     * @memberof ReleasePhasesApiReleasesByIdReleasePhasesGet
     */
    readonly page?: string

    /**
     * 
     * @type {string}
     * @memberof ReleasePhasesApiReleasesByIdReleasePhasesGet
     */
    readonly perPage?: string
}

/**
 * ReleasePhasesApi - object-oriented interface
 * @export
 * @class ReleasePhasesApi
 * @extends {BaseAPI}
 */
export class ReleasePhasesApi extends BaseAPI implements ReleasePhasesApiInterface {
    /**
     * 
     * @summary Delete a release phase
     * @param {ReleasePhasesApiReleasePhasesByIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleasePhasesApi
     */
    public releasePhasesByIdDelete(requestParameters: ReleasePhasesApiReleasePhasesByIdDeleteRequest, options?: RawAxiosRequestConfig) {
        return ReleasePhasesApiFp(this.configuration).releasePhasesByIdDelete(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a specific release phase
     * @param {ReleasePhasesApiReleasePhasesByIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleasePhasesApi
     */
    public releasePhasesByIdGet(requestParameters: ReleasePhasesApiReleasePhasesByIdGetRequest, options?: RawAxiosRequestConfig) {
        return ReleasePhasesApiFp(this.configuration).releasePhasesByIdGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a release phase
     * @param {ReleasePhasesApiReleasePhasesByIdPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleasePhasesApi
     */
    public releasePhasesByIdPut(requestParameters: ReleasePhasesApiReleasePhasesByIdPutRequest, options?: RawAxiosRequestConfig) {
        return ReleasePhasesApiFp(this.configuration).releasePhasesByIdPut(requestParameters.id, requestParameters.releasephasesPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List release phases in the account
     * @param {ReleasePhasesApiReleasePhasesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleasePhasesApi
     */
    public releasePhasesGet(requestParameters: ReleasePhasesApiReleasePhasesGetRequest = {}, options?: RawAxiosRequestConfig) {
        return ReleasePhasesApiFp(this.configuration).releasePhasesGet(requestParameters.page, requestParameters.perPage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a release milestone
     * @param {ReleasePhasesApiReleasePhasesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleasePhasesApi
     */
    public releasePhasesPost(requestParameters: ReleasePhasesApiReleasePhasesPostRequest, options?: RawAxiosRequestConfig) {
        return ReleasePhasesApiFp(this.configuration).releasePhasesPost(requestParameters.releasephasesPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List release phases for a release
     * @param {ReleasePhasesApiReleasesByIdReleasePhasesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReleasePhasesApi
     */
    public releasesByIdReleasePhasesGet(requestParameters: ReleasePhasesApiReleasesByIdReleasePhasesGetRequest, options?: RawAxiosRequestConfig) {
        return ReleasePhasesApiFp(this.configuration).releasesByIdReleasePhasesGet(requestParameters.id, requestParameters.page, requestParameters.perPage, options).then((request) => request(this.axios, this.basePath));
    }
}

