/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SchedulesGetResponse } from '../model';
/**
 * SchedulesApi - axios parameter creator
 */
export const SchedulesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves schedules for capacity planning, showing working hours, velocity, and weekly patterns
         * @summary List schedules
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {string} [fields] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        schedulesGet: async (page?: string, perPage?: string, fields?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/schedules`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (fields !== undefined) {
                localVarQueryParameter['fields'] = fields;
            }

            localVarHeaderParameter['Accept'] = 'application/json; charset=utf-8';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SchedulesApi - functional programming interface
 */
export const SchedulesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SchedulesApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves schedules for capacity planning, showing working hours, velocity, and weekly patterns
         * @summary List schedules
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {string} [fields] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async schedulesGet(page?: string, perPage?: string, fields?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SchedulesGetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.schedulesGet(page, perPage, fields, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchedulesApi.schedulesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SchedulesApi - factory interface
 */
export const SchedulesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SchedulesApiFp(configuration)
    return {
        /**
         * Retrieves schedules for capacity planning, showing working hours, velocity, and weekly patterns
         * @summary List schedules
         * @param {SchedulesApiSchedulesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        schedulesGet(requestParameters: SchedulesApiSchedulesGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<SchedulesGetResponse> {
            return localVarFp.schedulesGet(requestParameters.page, requestParameters.perPage, requestParameters.fields, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SchedulesApi - interface
 */
export interface SchedulesApiInterface {
    /**
     * Retrieves schedules for capacity planning, showing working hours, velocity, and weekly patterns
     * @summary List schedules
     * @param {SchedulesApiSchedulesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    schedulesGet(requestParameters?: SchedulesApiSchedulesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<SchedulesGetResponse>;

}

/**
 * Request parameters for schedulesGet operation in SchedulesApi.
 */
export interface SchedulesApiSchedulesGetRequest {
    readonly page?: string

    readonly perPage?: string

    readonly fields?: string
}

/**
 * SchedulesApi - object-oriented interface
 */
export class SchedulesApi extends BaseAPI implements SchedulesApiInterface {
    /**
     * Retrieves schedules for capacity planning, showing working hours, velocity, and weekly patterns
     * @summary List schedules
     * @param {SchedulesApiSchedulesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public schedulesGet(requestParameters: SchedulesApiSchedulesGetRequest = {}, options?: RawAxiosRequestConfig) {
        return SchedulesApiFp(this.configuration).schedulesGet(requestParameters.page, requestParameters.perPage, requestParameters.fields, options).then((request) => request(this.axios, this.basePath));
    }
}

