/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { TeammembersGetResponse } from '../model';
// @ts-ignore
import type { TeammembersPostRequest } from '../model';
// @ts-ignore
import type { TeammembersPostResponse } from '../model';
/**
 * TeamMembersApi - axios parameter creator
 */
export const TeamMembersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Manage virtual users used in capacity planning
         * @summary Delete a virtual team member
         * @param {string} id Id identifier
         * @param {TeammembersPostRequest} teammembersPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamMembersByIdDelete: async (id: string, teammembersPostRequest: TeammembersPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('teamMembersByIdDelete', 'id', id)
            // verify required parameter 'teammembersPostRequest' is not null or undefined
            assertParamExists('teamMembersByIdDelete', 'teammembersPostRequest', teammembersPostRequest)
            const localVarPath = `/team_members/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(teammembersPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Manage virtual users used in capacity planning
         * @summary List virtual team members
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamMembersGet: async (page?: string, perPage?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/team_members`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            localVarHeaderParameter['Accept'] = 'application/json; charset=utf-8';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Manage virtual users used in capacity planning
         * @summary Create a virtual user
         * @param {TeammembersPostRequest} teammembersPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamMembersPost: async (teammembersPostRequest: TeammembersPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'teammembersPostRequest' is not null or undefined
            assertParamExists('teamMembersPost', 'teammembersPostRequest', teammembersPostRequest)
            const localVarPath = `/team_members`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json; charset=utf-8';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(teammembersPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TeamMembersApi - functional programming interface
 */
export const TeamMembersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TeamMembersApiAxiosParamCreator(configuration)
    return {
        /**
         * Manage virtual users used in capacity planning
         * @summary Delete a virtual team member
         * @param {string} id Id identifier
         * @param {TeammembersPostRequest} teammembersPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async teamMembersByIdDelete(id: string, teammembersPostRequest: TeammembersPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.teamMembersByIdDelete(id, teammembersPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeamMembersApi.teamMembersByIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Manage virtual users used in capacity planning
         * @summary List virtual team members
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async teamMembersGet(page?: string, perPage?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TeammembersGetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.teamMembersGet(page, perPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeamMembersApi.teamMembersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Manage virtual users used in capacity planning
         * @summary Create a virtual user
         * @param {TeammembersPostRequest} teammembersPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async teamMembersPost(teammembersPostRequest: TeammembersPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TeammembersPostResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.teamMembersPost(teammembersPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TeamMembersApi.teamMembersPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TeamMembersApi - factory interface
 */
export const TeamMembersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TeamMembersApiFp(configuration)
    return {
        /**
         * Manage virtual users used in capacity planning
         * @summary Delete a virtual team member
         * @param {TeamMembersApiTeamMembersByIdDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamMembersByIdDelete(requestParameters: TeamMembersApiTeamMembersByIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.teamMembersByIdDelete(requestParameters.id, requestParameters.teammembersPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Manage virtual users used in capacity planning
         * @summary List virtual team members
         * @param {TeamMembersApiTeamMembersGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamMembersGet(requestParameters: TeamMembersApiTeamMembersGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<TeammembersGetResponse> {
            return localVarFp.teamMembersGet(requestParameters.page, requestParameters.perPage, options).then((request) => request(axios, basePath));
        },
        /**
         * Manage virtual users used in capacity planning
         * @summary Create a virtual user
         * @param {TeamMembersApiTeamMembersPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        teamMembersPost(requestParameters: TeamMembersApiTeamMembersPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TeammembersPostResponse> {
            return localVarFp.teamMembersPost(requestParameters.teammembersPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TeamMembersApi - interface
 */
export interface TeamMembersApiInterface {
    /**
     * Manage virtual users used in capacity planning
     * @summary Delete a virtual team member
     * @param {TeamMembersApiTeamMembersByIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    teamMembersByIdDelete(requestParameters: TeamMembersApiTeamMembersByIdDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Manage virtual users used in capacity planning
     * @summary List virtual team members
     * @param {TeamMembersApiTeamMembersGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    teamMembersGet(requestParameters?: TeamMembersApiTeamMembersGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<TeammembersGetResponse>;

    /**
     * Manage virtual users used in capacity planning
     * @summary Create a virtual user
     * @param {TeamMembersApiTeamMembersPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    teamMembersPost(requestParameters: TeamMembersApiTeamMembersPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<TeammembersPostResponse>;

}

/**
 * Request parameters for teamMembersByIdDelete operation in TeamMembersApi.
 */
export interface TeamMembersApiTeamMembersByIdDeleteRequest {
    /**
     * Id identifier
     */
    readonly id: string

    readonly teammembersPostRequest: TeammembersPostRequest
}

/**
 * Request parameters for teamMembersGet operation in TeamMembersApi.
 */
export interface TeamMembersApiTeamMembersGetRequest {
    readonly page?: string

    readonly perPage?: string
}

/**
 * Request parameters for teamMembersPost operation in TeamMembersApi.
 */
export interface TeamMembersApiTeamMembersPostRequest {
    readonly teammembersPostRequest: TeammembersPostRequest
}

/**
 * TeamMembersApi - object-oriented interface
 */
export class TeamMembersApi extends BaseAPI implements TeamMembersApiInterface {
    /**
     * Manage virtual users used in capacity planning
     * @summary Delete a virtual team member
     * @param {TeamMembersApiTeamMembersByIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public teamMembersByIdDelete(requestParameters: TeamMembersApiTeamMembersByIdDeleteRequest, options?: RawAxiosRequestConfig) {
        return TeamMembersApiFp(this.configuration).teamMembersByIdDelete(requestParameters.id, requestParameters.teammembersPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Manage virtual users used in capacity planning
     * @summary List virtual team members
     * @param {TeamMembersApiTeamMembersGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public teamMembersGet(requestParameters: TeamMembersApiTeamMembersGetRequest = {}, options?: RawAxiosRequestConfig) {
        return TeamMembersApiFp(this.configuration).teamMembersGet(requestParameters.page, requestParameters.perPage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Manage virtual users used in capacity planning
     * @summary Create a virtual user
     * @param {TeamMembersApiTeamMembersPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public teamMembersPost(requestParameters: TeamMembersApiTeamMembersPostRequest, options?: RawAxiosRequestConfig) {
        return TeamMembersApiFp(this.configuration).teamMembersPost(requestParameters.teammembersPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

