/* tslint:disable */
/* eslint-disable */
/**
 * Aha! API
 * Complete API documentation for Aha! generated from actual test responses
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { UsersGetResponse } from '../model';
// @ts-ignore
import type { UsersPostRequest } from '../model';
// @ts-ignore
import type { UsersPostResponse } from '../model';
// @ts-ignore
import type { UsersPutResponse } from '../model';
/**
 * UsersApi - axios parameter creator
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List users associated with a product
         * @param {string} productId ProductId identifier
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsByProductUsersGet: async (productId: string, page?: string, perPage?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('productsByProductUsersGet', 'productId', productId)
            const localVarPath = `/products/{product_id}/users`
                .replace('{product_id}', encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            localVarHeaderParameter['Accept'] = 'application/json; charset=utf-8';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a contributor user
         * @param {string} productId ProductId identifier
         * @param {UsersPostRequest} usersPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsByProductUsersPost: async (productId: string, usersPostRequest: UsersPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('productsByProductUsersPost', 'productId', productId)
            // verify required parameter 'usersPostRequest' is not null or undefined
            assertParamExists('productsByProductUsersPost', 'usersPostRequest', usersPostRequest)
            const localVarPath = `/products/{product_id}/users`
                .replace('{product_id}', encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json; charset=utf-8';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(usersPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a specific user
         * @param {string} id Id identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersByIdGet', 'id', id)
            const localVarPath = `/users/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json; charset=utf-8';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a user\'s product role
         * @param {string} id Id identifier
         * @param {string} productId ProductId identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdProductRolesByProductDelete: async (id: string, productId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersByIdProductRolesByProductDelete', 'id', id)
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('usersByIdProductRolesByProductDelete', 'productId', productId)
            const localVarPath = `/users/{id}/product_roles/{product_id}`
                .replace('{id}', encodeURIComponent(String(id)))
                .replace('{product_id}', encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List a user\'s product roles
         * @param {string} id Id identifier
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdProductRolesGet: async (id: string, page?: string, perPage?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersByIdProductRolesGet', 'id', id)
            const localVarPath = `/users/{id}/product_roles`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            localVarHeaderParameter['Accept'] = 'application/json; charset=utf-8';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a user\'s product roles
         * @param {string} id Id identifier
         * @param {UsersPostRequest} usersPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdProductRolesPost: async (id: string, usersPostRequest: UsersPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersByIdProductRolesPost', 'id', id)
            // verify required parameter 'usersPostRequest' is not null or undefined
            assertParamExists('usersByIdProductRolesPost', 'usersPostRequest', usersPostRequest)
            const localVarPath = `/users/{id}/product_roles`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json; charset=utf-8';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(usersPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a user
         * @param {string} id Id identifier
         * @param {UsersPostRequest} usersPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdPut: async (id: string, usersPostRequest: UsersPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersByIdPut', 'id', id)
            // verify required parameter 'usersPostRequest' is not null or undefined
            assertParamExists('usersByIdPut', 'usersPostRequest', usersPostRequest)
            const localVarPath = `/users/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json; charset=utf-8';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(usersPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a user\'s custom role
         * @param {string} id Id identifier
         * @param {string} productId ProductId identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdUserRolesByProductDelete: async (id: string, productId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersByIdUserRolesByProductDelete', 'id', id)
            // verify required parameter 'productId' is not null or undefined
            assertParamExists('usersByIdUserRolesByProductDelete', 'productId', productId)
            const localVarPath = `/users/{id}/user_roles/{product_id}`
                .replace('{id}', encodeURIComponent(String(id)))
                .replace('{product_id}', encodeURIComponent(String(productId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List a user\'s custom roles
         * @param {string} id Id identifier
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdUserRolesGet: async (id: string, page?: string, perPage?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersByIdUserRolesGet', 'id', id)
            const localVarPath = `/users/{id}/user_roles`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            localVarHeaderParameter['Accept'] = 'application/json; charset=utf-8';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a user\'s custom roles
         * @param {string} id Id identifier
         * @param {UsersPostRequest} usersPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdUserRolesPost: async (id: string, usersPostRequest: UsersPostRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('usersByIdUserRolesPost', 'id', id)
            // verify required parameter 'usersPostRequest' is not null or undefined
            assertParamExists('usersByIdUserRolesPost', 'usersPostRequest', usersPostRequest)
            const localVarPath = `/users/{id}/user_roles`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json; charset=utf-8';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(usersPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * **[Custom roles](https://www.aha.io/support/roadmaps/account/billing-and-users/custom-user-permission-roles) are an Enterprise+ exclusive feature.**
         * @summary List users
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersGet: async (page?: string, perPage?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication CookieAuth required

            // authentication OAuth2 required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2", [], configuration)

            // authentication ApiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            localVarHeaderParameter['Accept'] = 'application/json; charset=utf-8';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List users associated with a product
         * @param {string} productId ProductId identifier
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productsByProductUsersGet(productId: string, page?: string, perPage?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersGetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productsByProductUsersGet(productId, page, perPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.productsByProductUsersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a contributor user
         * @param {string} productId ProductId identifier
         * @param {UsersPostRequest} usersPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productsByProductUsersPost(productId: string, usersPostRequest: UsersPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersPostResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productsByProductUsersPost(productId, usersPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.productsByProductUsersPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a specific user
         * @param {string} id Id identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersByIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersGetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersByIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.usersByIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a user\'s product role
         * @param {string} id Id identifier
         * @param {string} productId ProductId identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersByIdProductRolesByProductDelete(id: string, productId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersByIdProductRolesByProductDelete(id, productId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.usersByIdProductRolesByProductDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List a user\'s product roles
         * @param {string} id Id identifier
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersByIdProductRolesGet(id: string, page?: string, perPage?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersGetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersByIdProductRolesGet(id, page, perPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.usersByIdProductRolesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a user\'s product roles
         * @param {string} id Id identifier
         * @param {UsersPostRequest} usersPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersByIdProductRolesPost(id: string, usersPostRequest: UsersPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersPostResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersByIdProductRolesPost(id, usersPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.usersByIdProductRolesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a user
         * @param {string} id Id identifier
         * @param {UsersPostRequest} usersPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersByIdPut(id: string, usersPostRequest: UsersPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersPutResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersByIdPut(id, usersPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.usersByIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a user\'s custom role
         * @param {string} id Id identifier
         * @param {string} productId ProductId identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersByIdUserRolesByProductDelete(id: string, productId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersByIdUserRolesByProductDelete(id, productId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.usersByIdUserRolesByProductDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List a user\'s custom roles
         * @param {string} id Id identifier
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersByIdUserRolesGet(id: string, page?: string, perPage?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersGetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersByIdUserRolesGet(id, page, perPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.usersByIdUserRolesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a user\'s custom roles
         * @param {string} id Id identifier
         * @param {UsersPostRequest} usersPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersByIdUserRolesPost(id: string, usersPostRequest: UsersPostRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersPostResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersByIdUserRolesPost(id, usersPostRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.usersByIdUserRolesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * **[Custom roles](https://www.aha.io/support/roadmaps/account/billing-and-users/custom-user-permission-roles) are an Enterprise+ exclusive feature.**
         * @summary List users
         * @param {string} [page] 
         * @param {string} [perPage] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersGet(page?: string, perPage?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UsersGetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersGet(page, perPage, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.usersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 
         * @summary List users associated with a product
         * @param {UsersApiProductsByProductUsersGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsByProductUsersGet(requestParameters: UsersApiProductsByProductUsersGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersGetResponse> {
            return localVarFp.productsByProductUsersGet(requestParameters.productId, requestParameters.page, requestParameters.perPage, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a contributor user
         * @param {UsersApiProductsByProductUsersPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsByProductUsersPost(requestParameters: UsersApiProductsByProductUsersPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersPostResponse> {
            return localVarFp.productsByProductUsersPost(requestParameters.productId, requestParameters.usersPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a specific user
         * @param {UsersApiUsersByIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdGet(requestParameters: UsersApiUsersByIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersGetResponse> {
            return localVarFp.usersByIdGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a user\'s product role
         * @param {UsersApiUsersByIdProductRolesByProductDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdProductRolesByProductDelete(requestParameters: UsersApiUsersByIdProductRolesByProductDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersByIdProductRolesByProductDelete(requestParameters.id, requestParameters.productId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List a user\'s product roles
         * @param {UsersApiUsersByIdProductRolesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdProductRolesGet(requestParameters: UsersApiUsersByIdProductRolesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersGetResponse> {
            return localVarFp.usersByIdProductRolesGet(requestParameters.id, requestParameters.page, requestParameters.perPage, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a user\'s product roles
         * @param {UsersApiUsersByIdProductRolesPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdProductRolesPost(requestParameters: UsersApiUsersByIdProductRolesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersPostResponse> {
            return localVarFp.usersByIdProductRolesPost(requestParameters.id, requestParameters.usersPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a user
         * @param {UsersApiUsersByIdPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdPut(requestParameters: UsersApiUsersByIdPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersPutResponse> {
            return localVarFp.usersByIdPut(requestParameters.id, requestParameters.usersPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a user\'s custom role
         * @param {UsersApiUsersByIdUserRolesByProductDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdUserRolesByProductDelete(requestParameters: UsersApiUsersByIdUserRolesByProductDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersByIdUserRolesByProductDelete(requestParameters.id, requestParameters.productId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List a user\'s custom roles
         * @param {UsersApiUsersByIdUserRolesGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdUserRolesGet(requestParameters: UsersApiUsersByIdUserRolesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersGetResponse> {
            return localVarFp.usersByIdUserRolesGet(requestParameters.id, requestParameters.page, requestParameters.perPage, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a user\'s custom roles
         * @param {UsersApiUsersByIdUserRolesPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersByIdUserRolesPost(requestParameters: UsersApiUsersByIdUserRolesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersPostResponse> {
            return localVarFp.usersByIdUserRolesPost(requestParameters.id, requestParameters.usersPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * **[Custom roles](https://www.aha.io/support/roadmaps/account/billing-and-users/custom-user-permission-roles) are an Enterprise+ exclusive feature.**
         * @summary List users
         * @param {UsersApiUsersGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersGet(requestParameters: UsersApiUsersGetRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<UsersGetResponse> {
            return localVarFp.usersGet(requestParameters.page, requestParameters.perPage, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - interface
 */
export interface UsersApiInterface {
    /**
     * 
     * @summary List users associated with a product
     * @param {UsersApiProductsByProductUsersGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    productsByProductUsersGet(requestParameters: UsersApiProductsByProductUsersGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersGetResponse>;

    /**
     * 
     * @summary Create a contributor user
     * @param {UsersApiProductsByProductUsersPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    productsByProductUsersPost(requestParameters: UsersApiProductsByProductUsersPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersPostResponse>;

    /**
     * 
     * @summary Get a specific user
     * @param {UsersApiUsersByIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    usersByIdGet(requestParameters: UsersApiUsersByIdGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersGetResponse>;

    /**
     * 
     * @summary Delete a user\'s product role
     * @param {UsersApiUsersByIdProductRolesByProductDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    usersByIdProductRolesByProductDelete(requestParameters: UsersApiUsersByIdProductRolesByProductDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary List a user\'s product roles
     * @param {UsersApiUsersByIdProductRolesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    usersByIdProductRolesGet(requestParameters: UsersApiUsersByIdProductRolesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersGetResponse>;

    /**
     * 
     * @summary Update a user\'s product roles
     * @param {UsersApiUsersByIdProductRolesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    usersByIdProductRolesPost(requestParameters: UsersApiUsersByIdProductRolesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersPostResponse>;

    /**
     * 
     * @summary Update a user
     * @param {UsersApiUsersByIdPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    usersByIdPut(requestParameters: UsersApiUsersByIdPutRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersPutResponse>;

    /**
     * 
     * @summary Delete a user\'s custom role
     * @param {UsersApiUsersByIdUserRolesByProductDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    usersByIdUserRolesByProductDelete(requestParameters: UsersApiUsersByIdUserRolesByProductDeleteRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary List a user\'s custom roles
     * @param {UsersApiUsersByIdUserRolesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    usersByIdUserRolesGet(requestParameters: UsersApiUsersByIdUserRolesGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersGetResponse>;

    /**
     * 
     * @summary Update a user\'s custom roles
     * @param {UsersApiUsersByIdUserRolesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    usersByIdUserRolesPost(requestParameters: UsersApiUsersByIdUserRolesPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersPostResponse>;

    /**
     * **[Custom roles](https://www.aha.io/support/roadmaps/account/billing-and-users/custom-user-permission-roles) are an Enterprise+ exclusive feature.**
     * @summary List users
     * @param {UsersApiUsersGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    usersGet(requestParameters?: UsersApiUsersGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<UsersGetResponse>;

}

/**
 * Request parameters for productsByProductUsersGet operation in UsersApi.
 */
export interface UsersApiProductsByProductUsersGetRequest {
    /**
     * ProductId identifier
     */
    readonly productId: string

    readonly page?: string

    readonly perPage?: string
}

/**
 * Request parameters for productsByProductUsersPost operation in UsersApi.
 */
export interface UsersApiProductsByProductUsersPostRequest {
    /**
     * ProductId identifier
     */
    readonly productId: string

    readonly usersPostRequest: UsersPostRequest
}

/**
 * Request parameters for usersByIdGet operation in UsersApi.
 */
export interface UsersApiUsersByIdGetRequest {
    /**
     * Id identifier
     */
    readonly id: string
}

/**
 * Request parameters for usersByIdProductRolesByProductDelete operation in UsersApi.
 */
export interface UsersApiUsersByIdProductRolesByProductDeleteRequest {
    /**
     * Id identifier
     */
    readonly id: string

    /**
     * ProductId identifier
     */
    readonly productId: string
}

/**
 * Request parameters for usersByIdProductRolesGet operation in UsersApi.
 */
export interface UsersApiUsersByIdProductRolesGetRequest {
    /**
     * Id identifier
     */
    readonly id: string

    readonly page?: string

    readonly perPage?: string
}

/**
 * Request parameters for usersByIdProductRolesPost operation in UsersApi.
 */
export interface UsersApiUsersByIdProductRolesPostRequest {
    /**
     * Id identifier
     */
    readonly id: string

    readonly usersPostRequest: UsersPostRequest
}

/**
 * Request parameters for usersByIdPut operation in UsersApi.
 */
export interface UsersApiUsersByIdPutRequest {
    /**
     * Id identifier
     */
    readonly id: string

    readonly usersPostRequest: UsersPostRequest
}

/**
 * Request parameters for usersByIdUserRolesByProductDelete operation in UsersApi.
 */
export interface UsersApiUsersByIdUserRolesByProductDeleteRequest {
    /**
     * Id identifier
     */
    readonly id: string

    /**
     * ProductId identifier
     */
    readonly productId: string
}

/**
 * Request parameters for usersByIdUserRolesGet operation in UsersApi.
 */
export interface UsersApiUsersByIdUserRolesGetRequest {
    /**
     * Id identifier
     */
    readonly id: string

    readonly page?: string

    readonly perPage?: string
}

/**
 * Request parameters for usersByIdUserRolesPost operation in UsersApi.
 */
export interface UsersApiUsersByIdUserRolesPostRequest {
    /**
     * Id identifier
     */
    readonly id: string

    readonly usersPostRequest: UsersPostRequest
}

/**
 * Request parameters for usersGet operation in UsersApi.
 */
export interface UsersApiUsersGetRequest {
    readonly page?: string

    readonly perPage?: string
}

/**
 * UsersApi - object-oriented interface
 */
export class UsersApi extends BaseAPI implements UsersApiInterface {
    /**
     * 
     * @summary List users associated with a product
     * @param {UsersApiProductsByProductUsersGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productsByProductUsersGet(requestParameters: UsersApiProductsByProductUsersGetRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).productsByProductUsersGet(requestParameters.productId, requestParameters.page, requestParameters.perPage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a contributor user
     * @param {UsersApiProductsByProductUsersPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productsByProductUsersPost(requestParameters: UsersApiProductsByProductUsersPostRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).productsByProductUsersPost(requestParameters.productId, requestParameters.usersPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a specific user
     * @param {UsersApiUsersByIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersByIdGet(requestParameters: UsersApiUsersByIdGetRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersByIdGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a user\'s product role
     * @param {UsersApiUsersByIdProductRolesByProductDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersByIdProductRolesByProductDelete(requestParameters: UsersApiUsersByIdProductRolesByProductDeleteRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersByIdProductRolesByProductDelete(requestParameters.id, requestParameters.productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List a user\'s product roles
     * @param {UsersApiUsersByIdProductRolesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersByIdProductRolesGet(requestParameters: UsersApiUsersByIdProductRolesGetRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersByIdProductRolesGet(requestParameters.id, requestParameters.page, requestParameters.perPage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a user\'s product roles
     * @param {UsersApiUsersByIdProductRolesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersByIdProductRolesPost(requestParameters: UsersApiUsersByIdProductRolesPostRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersByIdProductRolesPost(requestParameters.id, requestParameters.usersPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a user
     * @param {UsersApiUsersByIdPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersByIdPut(requestParameters: UsersApiUsersByIdPutRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersByIdPut(requestParameters.id, requestParameters.usersPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a user\'s custom role
     * @param {UsersApiUsersByIdUserRolesByProductDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersByIdUserRolesByProductDelete(requestParameters: UsersApiUsersByIdUserRolesByProductDeleteRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersByIdUserRolesByProductDelete(requestParameters.id, requestParameters.productId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List a user\'s custom roles
     * @param {UsersApiUsersByIdUserRolesGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersByIdUserRolesGet(requestParameters: UsersApiUsersByIdUserRolesGetRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersByIdUserRolesGet(requestParameters.id, requestParameters.page, requestParameters.perPage, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a user\'s custom roles
     * @param {UsersApiUsersByIdUserRolesPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersByIdUserRolesPost(requestParameters: UsersApiUsersByIdUserRolesPostRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersByIdUserRolesPost(requestParameters.id, requestParameters.usersPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * **[Custom roles](https://www.aha.io/support/roadmaps/account/billing-and-users/custom-user-permission-roles) are an Enterprise+ exclusive feature.**
     * @summary List users
     * @param {UsersApiUsersGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersGet(requestParameters: UsersApiUsersGetRequest = {}, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).usersGet(requestParameters.page, requestParameters.perPage, options).then((request) => request(this.axios, this.basePath));
    }
}

