name: Generate API Client
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write  # Required to push changes back to the repository

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clone aha-spec Repository
        run: |
          git clone https://github.com/cedricziel/aha-spec.git spec

      - name: Create Output Directory
        run: |
          mkdir -p src/generated

      - name: Generate TypeScript-Axios Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-axios
          openapi-file: spec/api/openapi.yaml
          config-file: generator-config.json
          command-args: --output=generated

      - name: Move Generated Files
        run: |
          rm -rf api docs model
          mv generated/* .
          rm -rf generated

      - name: Install Dependencies
        run: npm install

      - name: Build Package
        run: npm run build

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "fix: Update API client from latest spec" || echo "No changes to commit"
          git push
