name: Generate API Client
on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write  # Required to push changes back to the repository

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}

      - name: Clone aha-spec Repository
        run: |
          git clone https://github.com/cedricziel/aha-spec.git spec

      - name: Create Output Directory
        run: |
          mkdir -p src/generated

      - name: Generate TypeScript-Axios Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-axios
          openapi-file: spec/api/openapi.yaml
          config-file: generator-config.json
          command-args: --output=generated

      - name: Move Generated Files
        run: |
          rm -rf api docs model
          # Move only the directories we want, not package.json or other root files
          mv generated/api .
          mv generated/model .
          mv generated/docs .
          # Move TypeScript files but preserve our package.json
          find generated -name "*.ts" -maxdepth 1 -exec mv {} . \;
          rm -rf generated

      - name: Install Dependencies
        run: npm install

      - name: Build Package
        run: npm run build

      - name: Commit and Push Changes
        run: |
          git config --local user.email "cedricziel@users.noreply.github.com"
          git config --local user.name "Cedric Ziel"
          git add .

          # Get the latest commit hash from the spec repository
          SPEC_COMMIT=$(cd spec && git rev-parse --short HEAD)
          SPEC_DATE=$(cd spec && git log -1 --format=%cd --date=short)

          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            # Get summary of changes
            CHANGED_FILES=$(git diff --staged --name-only | wc -l | tr -d ' ')
            CHANGED_LIST=$(git diff --staged --name-only | sed 's/^/- /')

            # Create descriptive commit message with change summary
            git commit -m "fix: Update API client from spec ${SPEC_COMMIT} (${SPEC_DATE})

            Updated ${CHANGED_FILES} files from latest OpenAPI specification:

            ${CHANGED_LIST}"
            git push
          fi
